using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Reflection;
using System.Windows.Forms;
using MinimalFirewall.TypedObjects;

namespace MinimalFirewall
{
    public partial class WildcardRulesControl : UserControl
    {
        private WildcardRuleService? _wildcardRuleService;
        private BackgroundFirewallTaskService? _backgroundTaskService;
        private AppSettings? _appSettings;
        private BindingSource _bindingSource = new BindingSource();

        public WildcardRulesControl()
        {
            InitializeComponent();
            this.DoubleBuffered = true;

            wildcardDataGridView.AutoGenerateColumns = false;
            wildcardDataGridView.DataSource = _bindingSource;
        }

        public void Initialize(WildcardRuleService wildcardRuleService, BackgroundFirewallTaskService backgroundTaskService, AppSettings appSettings)
        {
            _wildcardRuleService = wildcardRuleService;
            _backgroundTaskService = backgroundTaskService;
            _appSettings = appSettings;

            foreach (DataGridViewColumn col in wildcardDataGridView.Columns)
            {
                col.SortMode = DataGridViewColumnSortMode.Programmatic;
            }
        }

        public void LoadRules()
        {
            if (_wildcardRuleService == null) return;

            var rules = _wildcardRuleService.GetRules();
            _bindingSource.DataSource = new BindingList<WildcardRule>(rules);
            _bindingSource.ResetBindings(false);
        }

        public void ClearRules()
        {
            _bindingSource.DataSource = null;
        }

        private void addRuleButton_Click(object sender, EventArgs e)
        {
            if (_wildcardRuleService == null || _appSettings == null || _backgroundTaskService == null) return;

            using var form = new WildcardCreatorForm(_wildcardRuleService, _appSettings);
            if (form.ShowDialog(this.FindForm()) == DialogResult.OK)
            {
                var newRule = form.NewRule;

                _backgroundTaskService.EnqueueTask(new FirewallTask(FirewallTaskType.AddWildcardRule, newRule));

                _bindingSource.Add(newRule);
                _bindingSource.ResetBindings(false);
            }
        }

        private void editRuleButton_Click(object sender, EventArgs e)
        {
            if (_wildcardRuleService == null || _appSettings == null || _backgroundTaskService == null) return;

            if (wildcardDataGridView.SelectedRows.Count != 1 || wildcardDataGridView.SelectedRows[0].DataBoundItem is not WildcardRule selectedRule)
            {
                MessageBox.Show("Please select a single rule to edit.", "Edit Rule", MessageBoxButtons.OK, MessageBoxIcon.Information);
                return;
            }

            using var form = new WildcardCreatorForm(_wildcardRuleService, _appSettings, selectedRule);
            if (form.ShowDialog(this.FindForm()) == DialogResult.OK)
            {
                var updatedRule = form.NewRule;
                var payload = new UpdateWildcardRulePayload { OldRule = selectedRule, NewRule = updatedRule };

                _backgroundTaskService.EnqueueTask(new FirewallTask(FirewallTaskType.UpdateWildcardRule, payload));

                int index = _bindingSource.IndexOf(selectedRule);
                if (index >= 0)
                {
                    _bindingSource[index] = updatedRule;
                    _bindingSource.ResetBindings(false);
                }
            }
        }

        private void deleteRuleButton_Click(object sender, EventArgs e)
        {
            if (wildcardDataGridView.SelectedRows.Count == 0 || _backgroundTaskService == null) return;

            var result = MessageBox.Show($"Are you sure you want to delete {wildcardDataGridView.SelectedRows.Count} rule definition(s)? This will also remove any firewall rules created by them.", "Confirm Deletion", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);

            if (result == DialogResult.Yes)
            {
                DeleteSelectedRules(FirewallTaskType.RemoveWildcardRule, removeFromUi: true);
            }
        }

        private void deleteDefinitionOnlyToolStripMenuItem_Click(object sender, EventArgs e)
        {
            if (wildcardDataGridView.SelectedRows.Count == 0) return;

            var result = MessageBox.Show($"Are you sure you want to delete the selected {wildcardDataGridView.SelectedRows.Count} wildcard definition(s)? Any existing rules already generated by them will NOT be deleted.", "Confirm Action", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);

            if (result == DialogResult.Yes)
            {
                DeleteSelectedRules(FirewallTaskType.RemoveWildcardDefinitionOnly, removeFromUi: true);
            }
        }

        private void deleteAllGeneratedRulesToolStripMenuItem_Click(object sender, EventArgs e)
        {
            if (wildcardDataGridView.SelectedRows.Count == 0) return;

            var result = MessageBox.Show($"Are you sure you want to delete all individual firewall rules generated by the selected {wildcardDataGridView.SelectedRows.Count} wildcard definition(s)? The definitions themselves will not be deleted.", "Confirm Action", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);

            if (result == DialogResult.Yes)
            {
                DeleteSelectedRules(FirewallTaskType.DeleteWildcardRules, removeFromUi: false);
                MessageBox.Show("The generated rules for the selected definitions have been queued for deletion.", "Task Queued", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }


        private void DeleteSelectedRules(FirewallTaskType taskType, bool removeFromUi)
        {
            var itemsToProcess = new List<WildcardRule>();
            foreach (DataGridViewRow row in wildcardDataGridView.SelectedRows)
            {
                if (row.DataBoundItem is WildcardRule rule)
                {
                    itemsToProcess.Add(rule);
                }
            }

            foreach (var rule in itemsToProcess)
            {
                var payload = new DeleteWildcardRulePayload { Wildcard = rule };
                _backgroundTaskService?.EnqueueTask(new FirewallTask(taskType, payload));

                if (removeFromUi)
                {
                    _bindingSource.Remove(rule);
                }
            }

            if (removeFromUi)
            {
                _bindingSource.ResetBindings(false);
            }
        }

        private void wildcardDataGridView_CellFormatting(object sender, DataGridViewCellFormattingEventArgs e)
        {
            if (e.RowIndex < 0 || e.RowIndex >= _bindingSource.Count) return;

            if (_bindingSource[e.RowIndex] is WildcardRule rule)
            {
                var column = wildcardDataGridView.Columns[e.ColumnIndex];
                if (column.DataPropertyName == "Protocol")
                {
                    e.Value = rule.Protocol switch
                    {
                        6 => "TCP",
                        17 => "UDP",
                        _ => "Any",
                    };
                    e.FormattingApplied = true;
                }
            }
        }

        private void wildcardDataGridView_ColumnHeaderMouseClick(object sender, DataGridViewCellMouseEventArgs e)
        {
            if (e.ColumnIndex < 0 || _bindingSource.DataSource is not BindingList<WildcardRule> list) return;

            var column = wildcardDataGridView.Columns[e.ColumnIndex];
            string propertyName = column.DataPropertyName;
            if (string.IsNullOrEmpty(propertyName)) return;

            bool ascending = column.HeaderCell.SortGlyphDirection != SortOrder.Ascending;
            List<WildcardRule> sortedRules = ascending
                ? list.OrderBy(r => GetPropertyValue(r, propertyName)).ToList()
                : list.OrderByDescending(r => GetPropertyValue(r, propertyName)).ToList();

            _bindingSource.DataSource = new BindingList<WildcardRule>(sortedRules);

            foreach (DataGridViewColumn col in wildcardDataGridView.Columns)
            {
                col.HeaderCell.SortGlyphDirection = SortOrder.None;
            }
            column.HeaderCell.SortGlyphDirection = ascending ? SortOrder.Ascending : SortOrder.Descending;
        }

        private static object? GetPropertyValue(WildcardRule rule, string propertyName)
        {
            return typeof(WildcardRule).GetProperty(propertyName)?.GetValue(rule);
        }
    }
}